baseurl = "/"
languageCode = "en"
contentDir = "content"
title = "Airspace"
#Hugo version = 0.55.6
#Hugo_version_link = "https://github.com/gohugoio/hugo/releases/tag/v0.55.6/"
multi_author = false
Paginate = 2



[Params.logo]
  logo = "/images/logo.png"

# Contact Information
[Params]
  mobile = "0124857985320"
  email = "demo@email.com"
  location = "North Main Street,Brooklyn Australia"

 copyright= "Copyright @ 2019"
 copyrightvar= "All Rights Reserved"
 ctatitle = "We design delightful digital experiences."
 ctadescription = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."
 ctaname = "Tell Us Your Story"
 ctaurl = "/contact/"




[[menu.main]]
name = "Home"
URL = "/"
weight = 1


[[menu.main]]
name = "About"
URL = "/about/"
weight = 2

[[menu.main]]
name = "Project"
URL = "/project/"
weight = 3

[[menu.main]]
name = "Service"
URL = "/service/"
weight = 4

[[menu.main]]
name = "Blog"
URL = "/blog/"
weight = 5

[[menu.main]]
weight = 6
name = "Pages"
hasChildren = true

  [[menu.main]]
  parent = "Pages"
  name = "FAQ"
  URL = "/faq/"

  [[menu.main]]
  parent = "Pages"
  name = "Pricing"
  URL = "/pricing/"
  
[[menu.main]]
name = "Contact"
URL = "/contact/"
weight = 7


  
 


# footer menu
[[menu.footer]]
name = "About"
URL = "about"
weight = 1

[[menu.footer]]
name = "Project"
URL = "project"
weight = 2

[[menu.footer]]
name = "Service"
URL = "service"
weight = 3

[[menu.footer]]
name = "Pricing"
URL = "pricing"
weight = 4

[[menu.footer]]
name = "FAQ"
URL = "faq"
weight = 5

[[menu.footer]]
name = "Contact"
URL = "contact"
weight = 6




# google map
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"







# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false


